repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-simplify, flake8-return]
        args: ["--max-line-length", "120", "--exclude=*.mdl"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-ast
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: check-yaml
      exclude: \.mdl$
    - id: end-of-file-fixer
      exclude: \.mdl$
    - id: trailing-whitespace
      exclude: \.mdl$
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        additional_dependencies:
        - tomli
        args: ["--skip", "*.mdl"]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
