[tool.black]
line-length = 120
target-version = ['py310']

[tool.flake8]
max-line-length = 120

[tool.isort]

py_version = 310
line_length = 120
group_by_package = true

# Files to skip
skip_glob = ["logs/*","data/*", "_isaac_sim/*"]



# Known third party packages with known types

known_third_party = [
    "omni.isaac.core",
    "omni.replicator.isaac",
    "omni.replicator.core",
    "pxr",
    "omni.kit.*",
    "warp",
    "carb",
]

known_first_party = "rover_envs"
